default_method_hyperparameters:
  targets_path: data/optimizer_targets/harmbench_targets_text.json
  masking_model: gpt-4-0613
  masking_model_key: your-key-here
  masking_direction: horizontal # "vertical"
  fontname: cards # ['gen', 'alphabet','letters','keyboard','cards','puzzle','gen']

<model_name1>:
  target_model: <model_name1>['model']

