default_method_hyperparameters:
    num_steps: 100
    eval_steps: 5
    num_test_cases_per_behavior: 1
    batch_size: 64 # number of parallel mutations
    num_elites: 0.1
    crossover: 0.5
    num_points: 5
    mutation: 0.01
    eval_with_check_refusal: True
    targets_path: ./data/optimizer_targets/harmbench_targets_text.json

    # using gpt mutate model
    # mutate_target_model:
    #   model_name_or_path: gpt-3.5-turbo-1106
    #   token: <openai_api_token>

    # using open-source mutate model
    mutate_model:
      model_name_or_path: /root/autodl-tmp/tools/hfd/gemma-7b-it
      use_vllm: True
      num_gpus: 1
      dtype: bfloat16
        # uncomment this to use toghether api instead of gpus, will override num_gpus
        # together_api_key: <together_api_key>

test: 
  num_steps: 1
  target_model:
    model_name_or_path: /root/autodl-tmp/tools/hfd/gemma-7b-it
    use_fast_tokenizer: False
    use_flash_attention_2: True
    num_gpus: 1
    model_short_name: Vicuna # AutoDan's original implementation has a placeholder for model name in prompts
    developer_name: LMSYS # AutoDan's original implementation has a placeholder for developer name/company in prompts
    chat_template: vicuna


vicuna_7b_v1_5:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    use_flash_attention_2: True
    model_short_name: Vicuna # AutoDAN's original implementation has a placeholder for model name in prompts
    developer_name: LMSYS # AutoDAN's original implementation has a placeholder for developer name/company in prompts
    chat_template: <model_name1>['model']['chat_template']

vicuna_13b_v1_5:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    use_flash_attention_2: True
    num_gpus: 1
    model_short_name: Vicuna # AutoDAN's original implementation has a placeholder for model name in prompts
    developer_name: LMSYS # AutoDAN's original implementation has a placeholder for developer name/company in prompts
    chat_template: <model_name1>['model']['chat_template']

zephyr_7b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    use_flash_attention_2: True
    model_short_name: Zephyr
    developer_name: Hugging Face

zephyr_7b_robust6_data2:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    dtype: bfloat16
    model_short_name: Zephyr
    developer_name: Hugging Face

koala_7b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    dtype: bfloat16
    developer_name: UC Berkeley
    model_short_name: Koala
    chat_template: <model_name1>['model']['chat_template']

koala_13b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    dtype: bfloat16
    developer_name: UC Berkeley
    model_short_name: Koala
    chat_template: <model_name1>['model']['chat_template']

starling_7b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    use_flash_attention_2: True
    model_short_name: GPT-4 # try ask the model `who are you?`
    developer_name: OpenAI
    dtype: bfloat16

openchat_3_5_1210:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    use_flash_attention_2: True
    model_short_name: GPT-4 # try ask the model `who are you?`
    developer_name: OpenAI
    dtype: bfloat16

llama2_7b:
  num_test_cases_per_behavior: 1
  eval_steps: 25
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    num_gpus: 1
    dtype: bfloat16
    model_short_name: Llama-2 # AutoDAN's original implementation has a placeholder for model name in prompts
    developer_name: Meta # AutoDAN's original implementation has a placeholder for developer name/company in prompts
    chat_template: <model_name1>['model']['chat_template']

llama2_7b_chat:
  num_test_cases_per_behavior: 1
  eval_steps: 25
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    num_gpus: 1
    dtype: bfloat16
    model_short_name: Llama-2 # AutoDAN's original implementation has a placeholder for model name in prompts
    developer_name: Meta # AutoDAN's original implementation has a placeholder for developer name/company in prompts
    chat_template: <model_name1>['model']['chat_template']

llama2_13b:
  eval_steps: 25
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    num_gpus: 2
    dtype: bfloat16
    model_short_name: Llama-2 # AutoDAN's original implementation has a placeholder for model name in prompts
    developer_name: Meta # AutoDAN's original implementation has a placeholder for developer name/company in prompts
    chat_template: <model_name1>['model']['chat_template']

llama2_70b:
  eval_steps: 25
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    num_gpus: 2
    dtype: bfloat16
    model_short_name: Llama-2 # AutoDAN's original implementation has a placeholder for model name in prompts
    developer_name: Meta # AutoDAN's original implementation has a placeholder for developer name/company in prompts
    chat_template: <model_name1>['model']['chat_template']

orca_2_7b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    use_flash_attention_2: True
    num_gpus: 1
    dtype: bfloat16
    model_short_name: Orca # AutoDAN's original implementation has a placeholder for model name in prompts
    developer_name: Microsoft # AutoDAN's original implementation has a placeholder for developer name/company in prompts
    chat_template: <model_name1>['model']['chat_template']

orca_2_13b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    use_flash_attention_2: True
    num_gpus: 1
    dtype: bfloat16
    model_short_name: Orca # AutoDAN's original implementation has a placeholder for model name in prompts
    developer_name: Microsoft # AutoDAN's original implementation has a placeholder for developer name/company in prompts
    chat_template: <model_name1>['model']['chat_template']

baichuan2_7b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    dtype: bfloat16
    trust_remote_code: True
    model_short_name: Baichuan
    developer_name: Baichuan
    num_gpus: 2
    chat_template: <model_name1>['model']['chat_template']
  forward_batch_size: 16

baichuan2_13b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    dtype: bfloat16
    trust_remote_code: True
    model_short_name: Baichuan
    developer_name: Baichuan
    device_map: balanced_low_0
    num_gpus: 2
    chat_template: <model_name1>['model']['chat_template']
  forward_batch_size: 8 # setting forward_batch_size because implementation has a lot of cache after each auto_find_batch_size OOM: #https://github.com/QwenLM/Qwen/issues/538


solar_10_7b_instruct:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    dtype: float16
    trust_remote_code: True
    model_short_name: GPT
    developer_name: OpenAI
    num_gpus: 1


mistral_7b_v2:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    dtype: bfloat16
    trust_remote_code: True
    model_short_name: Mistral
    developer_name: Mistral AI
    num_gpus: 1
    chat_template: <model_name1>['model']['chat_template']

mixtral_8x7b:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: False
    dtype: bfloat16
    trust_remote_code: True
    model_short_name: Mistral
    developer_name: Mistral AI
    num_gpus: 2
    chat_template: <model_name1>['model']['chat_template']

qwen_7b_chat:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: True
    trust_remote_code: True
    use_flash_attn: True
    dtype: bfloat16
    pad_token: <|extra_0|>
    eos_token: <|endoftext|>
    model_short_name: QianWen
    developer_name: Alibaba Cloud
    num_gpus: 2
    chat_template: <model_name1>['model']['chat_template']
  forward_batch_size: 16 # setting forward_batch_size because implementation of qwen have a lot of cache after each auto_find_batch_size OOM: #https://github.com/QwenLM/Qwen/issues/538

qwen_14b_chat:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: True
    trust_remote_code: True
    use_flash_attn: True
    dtype: bfloat16
    pad_token: <|extra_0|>
    eos_token: <|endoftext|>
    model_short_name: QianWen
    developer_name: Alibaba Cloud
    num_gpus: 2
    device_map: auto
    chat_template: <model_name1>['model']['chat_template']
  forward_batch_size: 8

qwen_72b_chat:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    use_fast_tokenizer: True
    trust_remote_code: True
    dtype: bfloat16
    pad_token: <|extra_0|>
    eos_token: <|endoftext|>
    model_short_name: QianWen
    developer_name: Alibaba Cloud
    num_gpus: 3
    chat_template: <model_name1>['model']['chat_template']
  forward_batch_size: 8
