default_method_hyperparameters:
  placeholder: placeholder

llava_v1_5:
  image_width: 336
  image_height: 336

instructblip:
  image_width: 224
  image_height: 224

qwen_vl_chat:
  image_width: 448
  image_height: 448

gpt4v:
  image_width: 224
  image_height: 224
