default_method_hyperparameters:
  num_steps: 1000
  step_size: 0.01
  targets_path: ./data/optimizer_targets/harmbench_targets_multimodal.json

<model_name1>:
  target_model: <model_name1>['model']

llava_v1_5:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    dtype: float16
  test_cases_batch_size: 1
  num_test_cases_per_behavior: 1

instructblip:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    dtype: float16
  test_cases_batch_size: 1
  num_test_cases_per_behavior: 1

qwen_vl_chat:
  target_model:
    model_name_or_path: <model_name1>['model']['model_name_or_path']
    dtype: float16
  test_cases_batch_size: 1
  num_test_cases_per_behavior: 1
