default_method_hyperparameters:
  # ===== Generation configs ======
  attack_gen_config:
    max_new_tokens: 2048
    temperature: 1.0
    stop_tokens: ['|']

top_5:
  attack_model:
    model_name_or_path: mistralai/Mixtral-8x7B-Instruct-v0.1
    use_vllm: True
    num_gpus: 2
    dtype: bfloat16
  top_k_persuasion_taxonomy: 5

full_40:
  attack_model:
    model_name_or_path: mistralai/Mixtral-8x7B-Instruct-v0.1
    use_vllm: True
    num_gpus: 2
    dtype: bfloat16
  top_k_persuasion_taxonomy: 40